name: Mana
options:
  bundleIdPrefix: com.pecknology
  deploymentTarget:
    macOS: "13.0"
targets:
  Mana:
    type: application
    platform: macOS
    sources:
      - Mana
    settings:
      base:
        PRODUCT_NAME: Mana
        PRODUCT_BUNDLE_IDENTIFIER: com.pecknology.Mana
        INFOPLIST_FILE: Mana/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Mana/Resources/Mana.entitlements
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      Release:
        CODE_SIGN_IDENTITY: "Developer ID Application"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 299R8V27FZ
    resources:
      - path: Mana/Resources
        buildPhase: resources
